### ISSUE TITLE
Bonus - If player types Specific colored word

### ISSUE THREAD

**Issue by phatyma** [chingu-voyages/v36-toucans-team-04#23]
As a player
When I type a bonus word indicated by a special color, I want to be rewarded
So that I can gain an additional Live to continue the game

- [x] Bonus word will spawn randomly at a very low chance and it will be more complex than the other words of the current difficulty level. 
- [x] Bonus word may have more letters in it or have a mix of uppercase and lowercase letters not found in regular words.
- [x]  Missing the bonus word should not penalize the player.

**Comment by mpark4656** [comment]
The bonus word should spawn now at a low rate (Every 100th word to be exact). The bonus word is currently more difficult in terms of falling speed only as it currently falls down approximately 60 pixels/s faster than regular words.

Since we have not designed game difficulty levels, I have not implemented a mix of uppercase/lowercase letters or a specific word length.
